@startuml ImageCaptionGenerator_UseCase
left to right direction
actor User as user

rectangle System {
  usecase "Upload Image" as UC1
  usecase "Select Language" as UC2
  usecase "Generate Caption" as UC3
  usecase "Translate Caption" as UC4
  usecase "View Results" as UC5
}

user --> UC1
user --> UC2
UC1 --> UC3
UC2 --> UC4
UC3 --> UC4
UC4 --> UC5
user --> UC5
@enduml